name: Gradle Package

on:
  push:
    branches: [ ci-enable ]

  pull_request:
    branches: [ ci-enable ]
  workflow_dispatch:


jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]


    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        
    # - name: Set up Git user identity
    #   run: |
    #     git config --global user.email "ci@example.com"
    #     git config --global user.name "CI Bot"

    # - name: Updating Git-submodule
    #   run: |
    #     git submodule update --init --recursive
    #     git submodule foreach --recursive git fetch
    #     git submodule foreach git merge origin master 

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        cache: gradle

    - name: Building jpf-symbc with Gradle
      run: |
        git submodule update --recursive
        ./gradlew :jpf-core:buildJars
        ./gradlew :jpf-symbc:buildJar
      
    - name: Testing jpf-symbc with Junit version 4.2
      run: |
        ./gradlew :jpf-symbc:test